title: "[(data, es. 4 Gennaio 2024)] Esercizio (numero, es. 2)"
labels: ["assegnare labels"]
body:
- type: dropdown
  id: subject
  attributes:
    label: Argomento
    options:
      - Combinatoria
      - Funzioni
      - Relazioni
      - Induzione
      - Logica
  validations:
    required: true
- type: textarea
  attributes:
    label: Traccia
    description: Incolla/inserisci qui uno screenshot della traccia dell'esercizio
  validations:
    required: true
- type: textarea
  attributes:
    label: Soluzione del professore
    description: Includi un'eventuale soluzione del professore (se in tuo possesso). Una volta completato l'inserimento della discussion potrai aggiungere, come commento, anche una tua eventuale proposta di soluzione 🙂
  validations:
    required: false
