title: "[<Argomento>] Esercizio <numero>"
labels: ["assegnare labels"]
body:
- type: dropdown
  id: subject
  attributes:
    label: Argomento
    options:
      - Insiemi, relazioni, funzioni
      - Numerabilità, equivalenza
      - Induzione
      - Logica
      - Altro
  validations:
    required: true
- type: textarea
  attributes:
    label: Traccia
    description: Incolla/inserisci qui uno screenshot della traccia dell'esercizio
  validations:
    required: true
- type: input
  attributes:
    label: Fonte
    description: Descrivi in quale dispensa, lezione o documento è stato originariamente distribuito questo esercizio (se di tua conoscenza)
  validations:
    required: false
- type: input
  attributes:
    label: Data di assegnazione
    description: Inserisci la data in cui l'esercizio è stato originariamente assegnato dal docente (se di tua conoscenza)
  validations:
    required: false
- type: textarea
  attributes:
    label: Soluzione del professore
    description: Includi un'eventuale soluzione del professore (se in tuo possesso). Una volta completato l'inserimento della discussion, se vuoi potrai aggiungere, come commento, anche una tua eventuale proposta di soluzione 🙂
  validations:
    required: false
